-- find the total sales across all the orders
SELECT SUM(SALES)FROM SALES.Orders  
-- find the total sales across all the orders
SELECT SUM(SALES),ORDERID FROM SALES.Orders   -- ERROR
SELECT SUM(SALES) OVER(),ORDERID,ORDERDATE FROM SALES.Orders

-- find the total sales FOR EACH PRODUCT
SELECT PRODUCTID, SUM(SALES) TOTAL_SALES FROM SALES.Orders GROUP BY PRODUCTID
-- we cant do aggregations and provide details at the same time using group by


-- find the total sales FOR EACH PRODUCT additionally provide details such as order id and order date
SELECT PRODUCTID, ORDERID
,SUM(SALES) OVER(PARTITION BY PRODUCTID) TOTAL_SALESBYPRODUCT
,ORDERDATE
FROM SALES.ORDERS
-- THE OUTPUT IS BY DEFAULT SORTED BY THE COL USED FOR PARTITIONING HERE (PRODUCTID)

-- ALLOWS AGGREGATION OF DATA AT DIFFERENT GRANULARITIES WITHIN THE SAME QUERY
SELECT PRODUCTID, ORDERID,SALES,
SUM(SALES) OVER() AS TOTALSALES,
SUM(SALES) OVER(PARTITION BY PRODUCTID) TOTAL_SALESBYPRODUCT,
SUM(SALES) OVER(PARTITION BY PRODUCTID,ORDERSTATUS) TOTAL_SALESBYPRODUCT_ANDSTATUS,
ORDERSTATUS, ORDERDATE
FROM SALES.ORDERS
-- THE OUTPUT IS BY DEFAULT SORTED BY THE COL USED FOR PARTITIONING HERE (PRODUCTID) AND THEN ORDERSTATUS AS SECONDARY SORT